import {
  BadRequestException,
  ConflictException,
  Injectable,
  Logger,
  NotFoundException,
} from '@nestjs/common';
import { Prisma } from '@ibms/db';
import { AuditService } from '../audit/audit.service';
import type { RecordAuditEntryInput } from '../audit/audit.service';
import { PrismaService } from '../prisma/prisma.service';
import type { AuthenticatedUser } from '../auth/auth.types';
import { formatMoney } from '../../common/money.util';

/**
 * Process 31–32 — Refund lifecycle (backlog Part C #31–32, Process 3.2 gap).
 * Handles refund disbursement (marking a refund as paid) and audit trail.
 *
 * Full refund lifecycle (standalone refund raise + approve + disburse) requires
 * schema migration to make Refund.endorsementId nullable (currently required
 * because refunds are only minted by negative Endorsements). This service
 * provides the disbursement path; standalone raise/approve are documented
 * future work (see IMPROVEMENTS.md §3.2).
 *
 * Refunds generated by Endorsements (cancellations, premium reductions) flow
 * through `EndorsementService.record()` which mints a Refund row. This service
 * provides the financial control: marking a refund as disbursed (paidAt) and
 * recording the audit trail.
 */
@Injectable()
export class RefundService {
  private readonly logger = new Logger(RefundService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
  ) {}

  /** Mark a refund as disbursed (paidAt = now). Idempotent — a second call for
   * an already-disbursed refund is a 409 (distinct from "refund doesn't exist"
   * 404). Audit trail is recorded on each call (not idempotent for audit).
   * No `ClientFundsLedgerEntry` is created here — that is the responsibility
   * of the caller's financial flow (e.g., a payment processing service). */
  async disburse(
    refundId: string,
    actor: AuthenticatedUser,
  ): Promise<{ id: string; paidAt: string }> {
    const refund = await this.prisma.client.refund.findUnique({
      where: { id: refundId },
    });

    if (!refund) {
      throw new NotFoundException(`Refund ${refundId} not found.`);
    }

    if (refund.paidAt !== null) {
      throw new ConflictException(
        `Refund ${refundId} was already disbursed on ${refund.paidAt.toISOString()}.`,
      );
    }

    const now = new Date();
    const updated = await this.prisma.client.refund.update({
      where: { id: refundId },
      data: { paidAt: now },
    });

    await this.safeAudit({
      userId: actor.id,
      action: 'UPDATE',
      entityType: 'Refund',
      entityId: refundId,
      afterValue: {
        refundId: updated.id,
        endorsementId: updated.endorsementId,
        amount: formatMoney(updated.amount),
        reason: updated.reason,
        raisedByUserId: updated.raisedByUserId,
        approvedByUserId: updated.approvedByUserId,
        paidAt: updated.paidAt ? updated.paidAt.toISOString() : null,
      },
    });

    return { id: updated.id, paidAt: updated.paidAt.toISOString() };
  }

  /** Audit failures never fail the request — the write has already committed
   * (same pattern as `PolicyService.safeAudit` / `InvoiceService.safeAudit`). */
  private async safeAudit(input: RecordAuditEntryInput): Promise<void> {
    try {
      await this.audit.record(input);
    } catch (err) {
      this.logger.error(
        `Refund audit record (${input.action} ${input.entityType} ${input.entityId}) failed after the operation already committed: ${(err as Error).message}`,
      );
    }
  }
}
