import { Injectable } from '@nestjs/common';
import type { Claim, Prisma, ThirdPartyClaimant } from '@ibms/db';
import { PrismaService } from '../prisma/prisma.service';

const CLAIM_INCLUDE = {
  thirdParty: true,
  statusHistory: { orderBy: { changedAt: 'asc' } },
  policy: {
    select: {
      id: true,
      customerId: true,
      policyNumber: true,
      insuranceLine: true,
      expiryDate: true,
      // Every PolicySchedule version — the materialised endorsement history a
      // Claim resolves "coverage in force at the loss date" against
      // (ibms-brain/meta/context/data-model.md). Oldest first so the resolver
      // can take the earliest `effectiveFrom` as the inception bound.
      schedules: {
        orderBy: { effectiveFrom: 'asc' },
        select: { id: true, effectiveFrom: true, effectiveTo: true },
      },
    },
  },
} as const;

/** Upper bound on a claims list response — a policy / customer with more
 * claims than this is extraordinary, and each row carries HIGHLY_CONFIDENTIAL
 * narrative, so an unbounded `findMany` would be an unbounded sensitive-data
 * read. The list is newest-first, so this returns the most recent N. */
export const CLAIM_LIST_LIMIT = 200;

/** A claim with its third-party child, its status-history trail and the parent
 * policy context (identity + every coverage-schedule window) — the shape every
 * claim read returns. */
export type ClaimWithContext = Prisma.ClaimGetPayload<{
  include: typeof CLAIM_INCLUDE;
}>;

export interface CreateClaimInput {
  policyId: string;
  customerId: string;
  lossDate: Date;
  lossLocation: string | null;
  causeOfLoss: string;
  estimatedLoss: Prisma.Decimal;
  isThirdPartyInvolved: boolean;
  isLargeClaim: boolean;
  /** The officer recording the notification — stamped on the opening
   * `ClaimStatusHistory` row (`fromStatus: null → NOTIFIED`), which is the
   * authoritative provenance trail for a claim (there is no
   * `Claim.notifiedByUserId` scalar; the AuditLogEntry CREATE row carries it
   * too). */
  notifiedByUserId: string;
}

export interface CreateThirdPartyClaimantInput {
  /** Pre-generated by the service so the field-level-encryption key-use audit
   * (`EncryptionService.encrypt`) attributes to the real row id. */
  id: string;
  fullName: string | null;
  /** Already field-level encrypted by the caller (`-- ENCRYPT`). */
  contactDetailsEnc: string | null;
  subrogationRecoveryFlag: boolean;
}

/**
 * Process 23 — Claim Notification (backlog Part C #23, Domain C). Owns `Claim`
 * plus its notification-time children: the opening `ClaimStatusHistory` row
 * and, for a third-party-involved loss, the one `ThirdPartyClaimant`.
 *
 * `Claim` IS a `WorkflowTransitionService` entity — its `status`
 * (`ClaimStatus`) moves ONLY through the engine
 * (ibms-brain/meta/lex/workflow-state-transitions.md). Nothing here writes
 * `status`: the notification row takes the schema `@default(NOTIFIED)` on
 * `create` (initial creation, same as a `Policy` created at
 * `PLACEMENT_CONFIRMED`); the `NOTIFIED → REGISTERED` move is Process 24.
 */
@Injectable()
export class ClaimRepository {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Create the `Claim`, its opening `NOTIFIED` status-history row, and (when
   * the loss involves a third party) the `ThirdPartyClaimant` — in ONE
   * interactive transaction (a deliberate local exception to this codebase's
   * no-`$transaction` convention, like `quotation.repository.ts` /
   * `policy.repository.ts`), so a crash cannot leave a claim with no
   * status-history trail (which feeds Loss Ratio and Claims Analytics) or an
   * `isThirdPartyInvolved` claim with no claimant row.
   */
  createNotification(
    claim: CreateClaimInput,
    thirdParty: CreateThirdPartyClaimantInput | null,
  ): Promise<{ claim: Claim; thirdParty: ThirdPartyClaimant | null }> {
    return this.prisma.client.$transaction(async (tx) => {
      const created = await tx.claim.create({
        data: {
          policyId: claim.policyId,
          customerId: claim.customerId,
          lossDate: claim.lossDate,
          lossLocation: claim.lossLocation,
          causeOfLoss: claim.causeOfLoss,
          estimatedLoss: claim.estimatedLoss,
          isThirdPartyInvolved: claim.isThirdPartyInvolved,
          isLargeClaim: claim.isLargeClaim,
        },
      });
      await tx.claimStatusHistory.create({
        data: {
          claimId: created.id,
          fromStatus: null,
          toStatus: created.status,
          changedByUserId: claim.notifiedByUserId,
        },
      });
      const tp = thirdParty
        ? await tx.thirdPartyClaimant.create({
            data: {
              id: thirdParty.id,
              claimId: created.id,
              fullName: thirdParty.fullName,
              contactDetailsEnc: thirdParty.contactDetailsEnc,
              subrogationRecoveryFlag: thirdParty.subrogationRecoveryFlag,
            },
          })
        : null;
      return { claim: created, thirdParty: tp };
    });
  }

  findById(id: string): Promise<ClaimWithContext | null> {
    return this.prisma.client.claim.findUnique({
      where: { id },
      include: CLAIM_INCLUDE,
    });
  }

  findManyByPolicyId(policyId: string): Promise<ClaimWithContext[]> {
    return this.prisma.client.claim.findMany({
      where: { policyId },
      include: CLAIM_INCLUDE,
      orderBy: { createdAt: 'desc' },
      take: CLAIM_LIST_LIMIT,
    });
  }

  findManyByCustomerId(customerId: string): Promise<ClaimWithContext[]> {
    return this.prisma.client.claim.findMany({
      where: { customerId },
      include: CLAIM_INCLUDE,
      orderBy: { createdAt: 'desc' },
      take: CLAIM_LIST_LIMIT,
    });
  }
}
