import { Injectable } from '@nestjs/common';
import type {
  Adjuster,
  Claim,
  ClaimDocument,
  ClaimStatus,
  DataClassification,
  Document,
  Prisma,
  ThirdPartyClaimant,
} from '@ibms/db';
import { PrismaService } from '../prisma/prisma.service';

// Process 25 — the claim-documentation files, newest first, for the
// mandatory-checklist computation. Secondary sort by id so intra-batch order is
// stable (one attachDocuments $transaction gives every Document the same
// createdAt). Declared as a typed array outside CLAIM_INCLUDE — an `as const`
// on the include object would freeze this to a readonly tuple that
// Prisma.ClaimInclude rejects.
const CLAIM_DOCUMENTS_ORDER: Prisma.ClaimDocumentOrderByWithRelationInput[] = [
  { document: { createdAt: 'desc' } },
  { id: 'asc' },
];

const CLAIM_INCLUDE = {
  thirdParty: true,
  // Process 24 — the one loss adjuster assigned at registration (or null).
  adjuster: true,
  documents: {
    include: { document: true },
    orderBy: CLAIM_DOCUMENTS_ORDER,
  },
  statusHistory: { orderBy: { changedAt: 'asc' } },
  policy: {
    select: {
      id: true,
      customerId: true,
      policyNumber: true,
      insuranceLine: true,
      expiryDate: true,
      // Every PolicySchedule version — the materialised endorsement history a
      // Claim resolves "coverage in force at the loss date" against
      // (ibms-brain/meta/context/data-model.md). Oldest first so the resolver
      // can take the earliest `effectiveFrom` as the inception bound.
      schedules: {
        orderBy: { effectiveFrom: 'asc' },
        select: { id: true, effectiveFrom: true, effectiveTo: true },
      },
    },
  },
} as const;

/** Upper bound on a claims list response — a policy / customer with more
 * claims than this is extraordinary, and each row carries HIGHLY_CONFIDENTIAL
 * narrative, so an unbounded `findMany` would be an unbounded sensitive-data
 * read. The list is newest-first, so this returns the most recent N. */
export const CLAIM_LIST_LIMIT = 200;

/** A claim with its third-party child, its status-history trail and the parent
 * policy context (identity + every coverage-schedule window) — the shape every
 * claim read returns. */
export type ClaimWithContext = Prisma.ClaimGetPayload<{
  include: typeof CLAIM_INCLUDE;
}>;

export interface CreateClaimInput {
  policyId: string;
  customerId: string;
  lossDate: Date;
  lossLocation: string | null;
  causeOfLoss: string;
  estimatedLoss: Prisma.Decimal;
  isThirdPartyInvolved: boolean;
  isLargeClaim: boolean;
  /** The officer recording the notification — stamped on the opening
   * `ClaimStatusHistory` row (`fromStatus: null → NOTIFIED`), which is the
   * authoritative provenance trail for a claim (there is no
   * `Claim.notifiedByUserId` scalar; the AuditLogEntry CREATE row carries it
   * too). */
  notifiedByUserId: string;
}

export interface CreateThirdPartyClaimantInput {
  /** Pre-generated by the service so the field-level-encryption key-use audit
   * (`EncryptionService.encrypt`) attributes to the real row id. */
  id: string;
  fullName: string | null;
  /** Already field-level encrypted by the caller (`-- ENCRYPT`). */
  contactDetailsEnc: string | null;
  subrogationRecoveryFlag: boolean;
}

export interface AssignAdjusterInput {
  name: string;
  firm: string | null;
}

export interface ClaimDocumentInput {
  docType: string;
  classification: DataClassification;
  fileName: string;
  storageRef: string;
  uploadedByUserId: string;
}

export type ClaimDocumentWithFile = ClaimDocument & { document: Document };

/**
 * Process 23-26 — Claim Notification + Registration + Documentation +
 * Assessment (backlog Part C #23-26, Domain C). Owns `Claim` plus its
 * children: the `ClaimStatusHistory` trail, the one `ThirdPartyClaimant`
 * (#23), the one loss `Adjuster` (#24, its survey / investigation completion
 * stamps written in #26) and the `ClaimDocument` / `Document` file rows (#25).
 *
 * `Claim` IS a `WorkflowTransitionService` entity — its `status`
 * (`ClaimStatus`) moves ONLY through the engine
 * (ibms-brain/meta/lex/workflow-state-transitions.md). Nothing here writes
 * `status`: the notification row takes the schema `@default(NOTIFIED)` on
 * `create` (initial creation, same as a `Policy` created at
 * `PLACEMENT_CONFIRMED`); the `NOTIFIED → REGISTERED` move (#24) goes through
 * `WorkflowTransitionService.transition` in `ClaimService`, and only the
 * post-transition artefacts (the `REGISTERED` history row + the `Adjuster`)
 * are written here.
 */
@Injectable()
export class ClaimRepository {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Create the `Claim`, its opening `NOTIFIED` status-history row, and (when
   * the loss involves a third party) the `ThirdPartyClaimant` — in ONE
   * interactive transaction (a deliberate local exception to this codebase's
   * no-`$transaction` convention, like `quotation.repository.ts` /
   * `policy.repository.ts`), so a crash cannot leave a claim with no
   * status-history trail (which feeds Loss Ratio and Claims Analytics) or an
   * `isThirdPartyInvolved` claim with no claimant row.
   */
  createNotification(
    claim: CreateClaimInput,
    thirdParty: CreateThirdPartyClaimantInput | null,
  ): Promise<{ claim: Claim; thirdParty: ThirdPartyClaimant | null }> {
    return this.prisma.client.$transaction(async (tx) => {
      const created = await tx.claim.create({
        data: {
          policyId: claim.policyId,
          customerId: claim.customerId,
          lossDate: claim.lossDate,
          lossLocation: claim.lossLocation,
          causeOfLoss: claim.causeOfLoss,
          estimatedLoss: claim.estimatedLoss,
          isThirdPartyInvolved: claim.isThirdPartyInvolved,
          isLargeClaim: claim.isLargeClaim,
        },
      });
      await tx.claimStatusHistory.create({
        data: {
          claimId: created.id,
          fromStatus: null,
          toStatus: created.status,
          changedByUserId: claim.notifiedByUserId,
        },
      });
      const tp = thirdParty
        ? await tx.thirdPartyClaimant.create({
            data: {
              id: thirdParty.id,
              claimId: created.id,
              fullName: thirdParty.fullName,
              contactDetailsEnc: thirdParty.contactDetailsEnc,
              subrogationRecoveryFlag: thirdParty.subrogationRecoveryFlag,
            },
          })
        : null;
      return { claim: created, thirdParty: tp };
    });
  }

  /**
   * Process 24 — the registration artefacts recorded once the
   * `NOTIFIED → REGISTERED` transition has committed: the `REGISTERED`
   * `ClaimStatusHistory` row (the engine writes only a generic `TRANSITION`
   * `AuditLogEntry`, not this domain trail that feeds Loss Ratio / Claims
   * Analytics) and the one loss `Adjuster` (`claimId @unique`) — in ONE
   * interactive transaction (the same local-exception rationale as
   * `createNotification`).
   *
   * "One `REGISTERED` history row per claim" is structural — the partial-free
   * `@@unique([claimId, toStatus])` on `ClaimStatusHistory` (migration
   * `20260902180000`, correct because `WORKFLOW_TRANSITIONS.Claim` is an
   * acyclic DAG). The `count()` here is a friendly pre-check that KEEPS the
   * crash-recovery re-entry working: a resume (transition committed, this
   * write did not, but a prior attempt DID insert the history row) must skip
   * the insert rather than roll the whole transaction back on the constraint.
   * A `P2002` on either insert (a concurrent registration got there first)
   * rolls the transaction back; the caller maps it to 409.
   */
  recordRegistration(input: {
    claimId: string;
    changedByUserId: string;
    adjuster: AssignAdjusterInput;
  }): Promise<Adjuster> {
    return this.prisma.client.$transaction(async (tx) => {
      const hasRegisteredHistory =
        (await tx.claimStatusHistory.count({
          where: { claimId: input.claimId, toStatus: 'REGISTERED' },
        })) > 0;
      if (!hasRegisteredHistory) {
        await tx.claimStatusHistory.create({
          data: {
            claimId: input.claimId,
            // REGISTERED's only predecessor in WORKFLOW_TRANSITIONS.Claim.
            fromStatus: 'NOTIFIED',
            toStatus: 'REGISTERED',
            changedByUserId: input.changedByUserId,
          },
        });
      }
      return tx.adjuster.create({
        data: {
          claimId: input.claimId,
          name: input.adjuster.name,
          firm: input.adjuster.firm,
        },
      });
    });
  }

  /**
   * Process 25 — attach one or more documentation files to a claim: each is a
   * `Document` row (the electronic Insurance File object, Part 4.2 — a
   * `storageRef` pointer, never the bytes) plus a `ClaimDocument` join carrying
   * the claim-specific `docType`. ONE interactive transaction (the same
   * local-exception rationale as `createNotification`) so a crash cannot leave
   * a `Document` with no `ClaimDocument` (an orphan in the file). The
   * `Document` is NOT linked to a `Policy` — the canonical link is the
   * `ClaimDocument` join; a future "full insurance file" view unions the two.
   */
  attachDocuments(
    claimId: string,
    documents: ClaimDocumentInput[],
  ): Promise<ClaimDocumentWithFile[]> {
    return this.prisma.client.$transaction(async (tx) => {
      const created: ClaimDocumentWithFile[] = [];
      for (const doc of documents) {
        const document = await tx.document.create({
          data: {
            category: 'CLAIM',
            classification: doc.classification,
            fileName: doc.fileName,
            storageRef: doc.storageRef,
            uploadedByUserId: doc.uploadedByUserId,
          },
        });
        const link = await tx.claimDocument.create({
          data: { claimId, documentId: document.id, docType: doc.docType },
        });
        created.push({ ...link, document });
      }
      return created;
    });
  }

  /**
   * Process 26 — stamp the loss `Adjuster`'s survey / investigation completion
   * timestamps. Each field is written with a `<field> IS NULL` guard so it is
   * **write-once** and a concurrent stamp loses the race (0 rows) rather than
   * being silently overwritten (`race-safe-invariants.md` — "guard right at
   * the write"). Returns the fresh row **and** which fields this call actually
   * wrote (`wrote.*`), so the service can 409 a caller whose value lost the
   * race to a *different* concurrent value rather than feign success. A patch
   * with no fields is a no-op reload (`wrote` all false).
   */
  async recordAdjusterProgress(
    claimId: string,
    patch: { surveyCompletedAt?: Date; investigationCompletedAt?: Date },
  ): Promise<{
    adjuster: Adjuster;
    wrote: { surveyCompletedAt: boolean; investigationCompletedAt: boolean };
  }> {
    const wrote = {
      surveyCompletedAt: false,
      investigationCompletedAt: false,
    };
    if (patch.surveyCompletedAt !== undefined) {
      const { count } = await this.prisma.client.adjuster.updateMany({
        where: { claimId, surveyCompletedAt: null },
        data: { surveyCompletedAt: patch.surveyCompletedAt },
      });
      wrote.surveyCompletedAt = count > 0;
    }
    if (patch.investigationCompletedAt !== undefined) {
      const { count } = await this.prisma.client.adjuster.updateMany({
        where: { claimId, investigationCompletedAt: null },
        data: { investigationCompletedAt: patch.investigationCompletedAt },
      });
      wrote.investigationCompletedAt = count > 0;
    }
    const adjuster = await this.prisma.client.adjuster.findUniqueOrThrow({
      where: { claimId },
    });
    return { adjuster, wrote };
  }

  /**
   * Process 25 — the domain `ClaimStatusHistory` row for a status the engine
   * has just moved through (the engine writes only a generic `TRANSITION`
   * `AuditLogEntry`, not this Analytics-feeding trail). Idempotent via the
   * `count()` pre-check + the structural `@@unique([claimId, toStatus])`
   * (migration `20260902180000`) — a best-effort caller can re-invoke it after
   * a partial failure without a duplicate row or a constraint bounce.
   */
  async recordStatusHistory(input: {
    claimId: string;
    fromStatus: ClaimStatus;
    toStatus: ClaimStatus;
    changedByUserId: string;
  }): Promise<void> {
    const already =
      (await this.prisma.client.claimStatusHistory.count({
        where: { claimId: input.claimId, toStatus: input.toStatus },
      })) > 0;
    if (already) return;
    await this.prisma.client.claimStatusHistory.create({
      data: {
        claimId: input.claimId,
        fromStatus: input.fromStatus,
        toStatus: input.toStatus,
        changedByUserId: input.changedByUserId,
      },
    });
  }

  findById(id: string): Promise<ClaimWithContext | null> {
    return this.prisma.client.claim.findUnique({
      where: { id },
      include: CLAIM_INCLUDE,
    });
  }

  findManyByPolicyId(policyId: string): Promise<ClaimWithContext[]> {
    return this.prisma.client.claim.findMany({
      where: { policyId },
      include: CLAIM_INCLUDE,
      orderBy: { createdAt: 'desc' },
      take: CLAIM_LIST_LIMIT,
    });
  }

  findManyByCustomerId(customerId: string): Promise<ClaimWithContext[]> {
    return this.prisma.client.claim.findMany({
      where: { customerId },
      include: CLAIM_INCLUDE,
      orderBy: { createdAt: 'desc' },
      take: CLAIM_LIST_LIMIT,
    });
  }
}
