import { Injectable } from '@nestjs/common';
import { Prisma } from '@ibms/db';
import type {
  Customer,
  CustomerSource,
  CustomerStatus,
  CustomerType,
  DataClassification,
  Document,
  DocumentCategory,
  InteractionChannel,
  LanguagePreference,
  UltimateBeneficialOwner,
} from '@ibms/db';
import { PrismaService } from '../prisma/prisma.service';
import { expandSearchTerms } from '../common/name-transliteration.config';

export interface CreateCustomerInput {
  /** Part III §7 — omitted by the intake flow, where the column default
   * (PLATFORM) is already the truth. Set explicitly only by the legacy
   * importer, which must mark its rows as never having passed KYC here. */
  source?: CustomerSource;
  /** Pre-generated by CustomerService (crypto.randomUUID()) BEFORE this
   * call, so EncryptionService has a real entityId to attribute the
   * encrypt-time ENCRYPTION_KEY_USED audit rows to — the row does not exist
   * yet at the point encryption happens, so there is no id to read back
   * afterward the way most other create() calls work. */
  id: string;
  prospectId?: string;
  customerType: CustomerType;
  legalName: string;
  /** Individual only — Jordanian national-ID-convention name parts (Part F
   * item #4). Undefined for a CORPORATE customer. */
  givenName?: string;
  fatherName?: string;
  grandfatherName?: string;
  familyName?: string;
  registrationNumber?: string;
  /** Part B §11 — screening discriminators. Individual only. */
  dateOfBirth?: Date;
  nationality?: string;
  nationalIdEnc?: string;
  taxRegistrationNumber?: string;
  registeredAddress?: string;
  natureOfBusiness?: string;
  contactPhoneEnc?: string;
  contactEmailEnc?: string;
  languagePreference: LanguagePreference;
  preferredContactChannel?: InteractionChannel;
  ownerUserId: string;
}

export interface CustomerFilter {
  ownerUserId?: string;
  status?: CustomerStatus;
  /** Part F item #6 — pre-resolved ids from a full-text search
   * (searchIds()); undefined means no search filter is active. */
  id?: string[];
}

export interface CreateUboInput {
  /** Same pre-generated-id rationale as CreateCustomerInput.id above. */
  id: string;
  customerId: string;
  fullName: string;
  /** Jordanian national-ID-convention name parts (Part F item #4) — a UBO
   * is always a real individual, so unlike Customer these always apply. */
  givenName: string;
  fatherName?: string;
  grandfatherName?: string;
  familyName: string;
  nationalIdEnc: string;
  /** Part B §11 — screening discriminators. */
  dateOfBirth?: Date;
  nationality?: string;
  ownershipPercent?: Prisma.Decimal;
  isAuthorizedSignatory: boolean;
  isPep: boolean;
}

export interface CreateCustomerDocumentInput {
  customerId: string;
  category: DocumentCategory;
  classification: DataClassification;
  fileName: string;
  storageRef: string;
  uploadedByUserId: string;
}

/** Process 3-4 (Customer Acquisition/Onboarding) — Customer plus its two
 * customer-scoped child collections, UBO and (customer-owned) Document. Kept
 * in one repository, same "one repository per aggregate root" shape as
 * lead.repository.ts/prospect.repository.ts, since all three tables are
 * only ever read/written together through this one onboarding flow. */
@Injectable()
export class CustomerRepository {
  constructor(private readonly prisma: PrismaService) {}

  create(input: CreateCustomerInput): Promise<Customer> {
    return this.prisma.client.customer.create({ data: input });
  }

  /**
   * Correct a customer's CONTACT details. The first write to a `Customer` row this codebase has ever had
   * other than the create — see IMPROVEMENTS § 3.14.
   *
   * Only the three fields with no screening consequence. Widening this to a name or a date of birth would
   * put a screening event behind a repository method, which is exactly the shape the AMLU rules refuse:
   * those ship with the re-screening mechanism or not at all.
   */
  updateContactDetails(
    id: string,
    data: {
      contactPhoneEnc?: string;
      contactEmailEnc?: string;
      registeredAddress?: string;
    },
  ): Promise<Customer> {
    return this.prisma.client.customer.update({ where: { id }, data });
  }

  /**
   * Record a correction. The evidence the AMLU requires kept — "the verification mechanism and actions
   * taken … in internal records" — and, when `dsrId` is set, the evidence that a statutory request was
   * actually answered rather than attested to.
   */
  recordCorrection(input: {
    id: string;
    customerId: string;
    field: string;
    beforeValueEnc?: string;
    afterValueEnc?: string;
    reason: string;
    correctedByUserId: string;
    dsrId?: string;
    kycRecordId?: string;
    kycStatusBefore?: string;
    priorScreeningResultId?: string;
  }): Promise<{ id: string }> {
    return this.prisma.client.customerIdentifierCorrection.create({
      data: input,
      select: { id: true },
    });
  }

  /** How many corrections were recorded in answer to this request. The DSR closure gate's one query. */
  countCorrectionsForDsr(dsrId: string): Promise<number> {
    return this.prisma.client.customerIdentifierCorrection.count({
      where: { dsrId },
    });
  }

  findById(id: string): Promise<Customer | null> {
    return this.prisma.client.customer.findUnique({ where: { id } });
  }

  /** The `where` both the page query and its count run on, so they can never
   *  disagree about what is being counted. */
  private listWhere(filter: CustomerFilter) {
    return {
      ownerUserId: filter.ownerUserId,
      status: filter.status,
      id: filter.id ? { in: filter.id } : undefined,
    };
  }

  /** The window is REQUIRED, not optional. This has exactly one caller today
   *  (`CustomerService.list`), and an optional window would let the next one
   *  read the whole customer book by leaving an argument off — which is the
   *  unbounded query `common/pagination.ts` exists to remove. A caller that
   *  genuinely wants every match should say so with an explicit window. */
  findMany(
    filter: CustomerFilter,
    window: { take: number; skip: number },
  ): Promise<Customer[]> {
    return this.prisma.client.customer.findMany({
      where: this.listWhere(filter),
      orderBy: { createdAt: 'desc' },
      take: window.take,
      skip: window.skip,
    });
  }

  countMany(filter: CustomerFilter): Promise<number> {
    return this.prisma.client.customer.count({ where: this.listWhere(filter) });
  }

  /** Part F item #6 — bilingual full-text search (Arabic + English) over
   * `legalName` only (never the encrypted contact fields). Concatenates
   * both the 'arabic' and 'english' text-search configs on both the
   * document (searchVector, generated by Postgres — see migration
   * 20260918120000_add_search_vectors) and the query side, so a search
   * term in either script matches — empirically verified against this
   * exact Postgres build before writing this query, not assumed.
   * `websearch_to_tsquery` (not raw `to_tsquery`) safely degrades
   * empty/punctuation-only input to an empty query rather than throwing,
   * and Prisma's tagged-template `$queryRaw` parameterizes `term` — this
   * is never SQL-injectable, confirmed empirically with an
   * injection-shaped test string before this was written.
   *
   * Part F item #6 remainder — fuzzy transliteration matching: `term` is
   * OR'd against every KNOWN variant spelling from
   * `expandSearchTerms()` (e.g. searching "Ahmad" also searches "أحمد"),
   * never a distance-based fuzzy guess — see that module's own doc for why
   * a fuzzy-distance matcher was rejected. Each variant is still its own
   * parameterized `websearch_to_tsquery(...)` call via `Prisma.sql`/
   * `Prisma.join` — no string concatenation, same SQL-injection guarantee
   * as the single-term case above. */
  async searchIds(term: string): Promise<string[]> {
    const terms = [term, ...expandSearchTerms(term)];
    const rows = await this.prisma.client.$queryRaw<{ id: string }[]>`
      SELECT id FROM "Customer"
      WHERE (${Prisma.join(
        terms.map(
          (t) => Prisma.sql`"searchVector" @@ (
            websearch_to_tsquery('arabic', ${t}) ||
            websearch_to_tsquery('english', ${t})
          )`,
        ),
        ' OR ',
      )})
    `;
    return rows.map((r) => r.id);
  }

  /**
   * The BOUNDED search behind `GET /customers/search` — the one field that finds a named customer.
   *
   * ## Three things it matches, and why the third is not the second
   *
   * The name, through the same bilingual full-text vector and transliteration expansion `searchIds`
   * uses, so "Ahmad" still finds "أحمد". Then the two CLEARTEXT identifier columns a corporate record
   * carries — the commercial registration number and the tax registration number — because a clerk
   * holding a document knows the number and not the spelling, which is the whole case for the field.
   *
   * The identifier match is a PREFIX (`startsWith`), not a contains. A contains on a number turns every
   * three-digit fragment into a wide scan of the book, which is condition 1 defeated by the thing meant
   * to satisfy condition 1. Case-insensitive because a registration number is printed with letters in
   * some series and nobody reads them off a document in a consistent case.
   *
   * ## WHAT IT CANNOT MATCH, and this is not an oversight
   *
   * An individual's NATIONAL ID and the contact PHONE are unreachable here. `nationalIdEnc`,
   * `contactPhoneEnc` and `contactEmailEnc` are encrypted with a RANDOM IV PER VALUE
   * (`randomBytes(12)`), so the same national ID stored twice is two different ciphertexts: there is no
   * equality to test and nothing to prefix-match. Making them searchable would mean a deterministic
   * encoding of a Highly Confidential identifier, which is the decision the masked national ID exists
   * to refuse. So the clerk's case is served for a company and NOT for a person, and that gap is a
   * decision for the owner rather than something to close quietly here.
   *
   * ## The window is REQUIRED
   *
   * Same argument as `findMany` above, and here it is the owner's condition 2 rather than a preference:
   * an optional bound would let the next caller read the whole book by leaving an argument off.
   */
  async searchForPicker(
    term: string,
    take: number,
    ownerUserId: string | undefined,
  ): Promise<Customer[]> {
    const terms = [term, ...expandSearchTerms(term)];
    const nameMatches = await this.prisma.client.$queryRaw<{ id: string }[]>`
      SELECT id FROM "Customer"
      WHERE (${Prisma.join(
        terms.map(
          (t) => Prisma.sql`"searchVector" @@ (
            websearch_to_tsquery('arabic', ${t}) ||
            websearch_to_tsquery('english', ${t})
          )`,
        ),
        ' OR ',
      )})
      LIMIT ${take}
    `;

    // Through the extension, NOT the raw client: this is the office-scoped read, and it is also what
    // re-applies tenancy to the ids the raw name query returned.
    return this.prisma.client.customer.findMany({
      where: {
        // The OWNER filter sits OUTSIDE the OR, deliberately. Inside it, a registration-number match
        // would ignore it and hand a Sales officer a customer belonging to a colleague — a search that
        // discloses more than the list it is a shortcut to. `undefined` means "every owner", which is
        // what a holder of the all-owners read gets and nobody else.
        ownerUserId,
        OR: [
          { id: { in: nameMatches.map((r) => r.id) } },
          { registrationNumber: { startsWith: term, mode: 'insensitive' } },
          { taxRegistrationNumber: { startsWith: term, mode: 'insensitive' } },
        ],
      },
      // A TOTAL order. `legalName` alone is not one — two customers of the same name would come back in
      // whatever order the plan chose, so which of them a bounded search truncated away would change
      // between identical requests. Same rule as `findActiveUserIdsWithPermission`, same reason.
      orderBy: [{ legalName: 'asc' }, { id: 'asc' }],
      take,
    });
  }

  /** Every ACTIVE customer — used by the recurring screening batch
   * (screening-batch.scheduler.ts) to find who a "material change" rerun
   * should cover. */
  findActive(): Promise<Customer[]> {
    return this.prisma.client.customer.findMany({
      where: { status: 'ACTIVE' },
    });
  }

  createUbo(input: CreateUboInput): Promise<UltimateBeneficialOwner> {
    return this.prisma.client.ultimateBeneficialOwner.create({
      data: input,
    });
  }

  findUbosByCustomerId(customerId: string): Promise<UltimateBeneficialOwner[]> {
    return this.prisma.client.ultimateBeneficialOwner.findMany({
      where: { customerId },
      orderBy: { createdAt: 'desc' },
    });
  }

  createDocument(input: CreateCustomerDocumentInput): Promise<Document> {
    return this.prisma.client.document.create({ data: input });
  }

  findDocumentsByCustomerId(customerId: string): Promise<Document[]> {
    return this.prisma.client.document.findMany({
      where: { customerId },
      orderBy: { createdAt: 'desc' },
    });
  }
}
