import { Injectable } from '@nestjs/common';
import { Prisma } from '@ibms/db';
import type {
  Customer,
  CustomerStatus,
  CustomerType,
  DataClassification,
  Document,
  DocumentCategory,
  InteractionChannel,
  LanguagePreference,
  UltimateBeneficialOwner,
} from '@ibms/db';
import { PrismaService } from '../prisma/prisma.service';
import { expandSearchTerms } from '../common/name-transliteration.config';

export interface CreateCustomerInput {
  /** Pre-generated by CustomerService (crypto.randomUUID()) BEFORE this
   * call, so EncryptionService has a real entityId to attribute the
   * encrypt-time ENCRYPTION_KEY_USED audit rows to — the row does not exist
   * yet at the point encryption happens, so there is no id to read back
   * afterward the way most other create() calls work. */
  id: string;
  prospectId?: string;
  customerType: CustomerType;
  legalName: string;
  /** Individual only — Jordanian national-ID-convention name parts (Part F
   * item #4). Undefined for a CORPORATE customer. */
  givenName?: string;
  fatherName?: string;
  grandfatherName?: string;
  familyName?: string;
  registrationNumber?: string;
  /** Part B §11 — screening discriminators. Individual only. */
  dateOfBirth?: Date;
  nationality?: string;
  nationalIdEnc?: string;
  taxRegistrationNumber?: string;
  registeredAddress?: string;
  natureOfBusiness?: string;
  contactPhoneEnc?: string;
  contactEmailEnc?: string;
  languagePreference: LanguagePreference;
  preferredContactChannel?: InteractionChannel;
  ownerUserId: string;
}

export interface CustomerFilter {
  ownerUserId?: string;
  status?: CustomerStatus;
  /** Part F item #6 — pre-resolved ids from a full-text search
   * (searchIds()); undefined means no search filter is active. */
  id?: string[];
}

export interface CreateUboInput {
  /** Same pre-generated-id rationale as CreateCustomerInput.id above. */
  id: string;
  customerId: string;
  fullName: string;
  /** Jordanian national-ID-convention name parts (Part F item #4) — a UBO
   * is always a real individual, so unlike Customer these always apply. */
  givenName: string;
  fatherName?: string;
  grandfatherName?: string;
  familyName: string;
  nationalIdEnc: string;
  /** Part B §11 — screening discriminators. */
  dateOfBirth?: Date;
  nationality?: string;
  ownershipPercent?: Prisma.Decimal;
  isAuthorizedSignatory: boolean;
  isPep: boolean;
}

export interface CreateCustomerDocumentInput {
  customerId: string;
  category: DocumentCategory;
  classification: DataClassification;
  fileName: string;
  storageRef: string;
  uploadedByUserId: string;
}

/** Process 3-4 (Customer Acquisition/Onboarding) — Customer plus its two
 * customer-scoped child collections, UBO and (customer-owned) Document. Kept
 * in one repository, same "one repository per aggregate root" shape as
 * lead.repository.ts/prospect.repository.ts, since all three tables are
 * only ever read/written together through this one onboarding flow. */
@Injectable()
export class CustomerRepository {
  constructor(private readonly prisma: PrismaService) {}

  create(input: CreateCustomerInput): Promise<Customer> {
    return this.prisma.client.customer.create({ data: input });
  }

  findById(id: string): Promise<Customer | null> {
    return this.prisma.client.customer.findUnique({ where: { id } });
  }

  findMany(filter: CustomerFilter): Promise<Customer[]> {
    return this.prisma.client.customer.findMany({
      where: {
        ownerUserId: filter.ownerUserId,
        status: filter.status,
        id: filter.id ? { in: filter.id } : undefined,
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  /** Part F item #6 — bilingual full-text search (Arabic + English) over
   * `legalName` only (never the encrypted contact fields). Concatenates
   * both the 'arabic' and 'english' text-search configs on both the
   * document (searchVector, generated by Postgres — see migration
   * 20260918120000_add_search_vectors) and the query side, so a search
   * term in either script matches — empirically verified against this
   * exact Postgres build before writing this query, not assumed.
   * `websearch_to_tsquery` (not raw `to_tsquery`) safely degrades
   * empty/punctuation-only input to an empty query rather than throwing,
   * and Prisma's tagged-template `$queryRaw` parameterizes `term` — this
   * is never SQL-injectable, confirmed empirically with an
   * injection-shaped test string before this was written.
   *
   * Part F item #6 remainder — fuzzy transliteration matching: `term` is
   * OR'd against every KNOWN variant spelling from
   * `expandSearchTerms()` (e.g. searching "Ahmad" also searches "أحمد"),
   * never a distance-based fuzzy guess — see that module's own doc for why
   * a fuzzy-distance matcher was rejected. Each variant is still its own
   * parameterized `websearch_to_tsquery(...)` call via `Prisma.sql`/
   * `Prisma.join` — no string concatenation, same SQL-injection guarantee
   * as the single-term case above. */
  async searchIds(term: string): Promise<string[]> {
    const terms = [term, ...expandSearchTerms(term)];
    const rows = await this.prisma.client.$queryRaw<{ id: string }[]>`
      SELECT id FROM "Customer"
      WHERE (${Prisma.join(
        terms.map(
          (t) => Prisma.sql`"searchVector" @@ (
            websearch_to_tsquery('arabic', ${t}) ||
            websearch_to_tsquery('english', ${t})
          )`,
        ),
        ' OR ',
      )})
    `;
    return rows.map((r) => r.id);
  }

  /** Every ACTIVE customer — used by the recurring screening batch
   * (screening-batch.scheduler.ts) to find who a "material change" rerun
   * should cover. */
  findActive(): Promise<Customer[]> {
    return this.prisma.client.customer.findMany({
      where: { status: 'ACTIVE' },
    });
  }

  createUbo(input: CreateUboInput): Promise<UltimateBeneficialOwner> {
    return this.prisma.client.ultimateBeneficialOwner.create({
      data: input,
    });
  }

  findUbosByCustomerId(customerId: string): Promise<UltimateBeneficialOwner[]> {
    return this.prisma.client.ultimateBeneficialOwner.findMany({
      where: { customerId },
      orderBy: { createdAt: 'desc' },
    });
  }

  createDocument(input: CreateCustomerDocumentInput): Promise<Document> {
    return this.prisma.client.document.create({ data: input });
  }

  findDocumentsByCustomerId(customerId: string): Promise<Document[]> {
    return this.prisma.client.document.findMany({
      where: { customerId },
      orderBy: { createdAt: 'desc' },
    });
  }
}
